# Generated by Django 4.2.5 on 2025-04-15 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UDProjectInformationAndInputs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UDPROJECT_ID', models.CharField(max_length=50, unique=True)),
                ('UDPROJECT_NAME', models.CharField(max_length=50)),
                ('UDCREATION_DATE', models.DateField(auto_now_add=True)),
                ('UDCREATION_TIME', models.TimeField(auto_now_add=True)),
                ('UDCREATED_BY', models.CharField(blank=True, null=True)),
                ('UDPROJECT_DESCRIPTION', models.TextField(blank=True, max_length=200, null=True)),
                ('UDCLIENT_ORGANIZATION', models.CharField(max_length=50)),
                ('UDEXECUTED_ORGANIZATION', models.CharField(max_length=50)),
                ('UDCROPPING_YEAR', models.CharField(blank=True, null=True)),
                ('UDCROPPING_SEASON', models.CharField(blank=True, null=True)),
                ('UDAREA_INFORMATION', models.TextField(blank=True, null=True)),
                ('UDWORKSPACE_LOCATION', models.CharField()),
                ('UDPROJECT_FOLDER', models.CharField()),
                ('UDPROJECT_INFORMATION', models.CharField()),
                ('UDAREA_OF_INTEREST', models.CharField(blank=True, null=True)),
                ('UDGROUND_TRUTH', models.CharField(blank=True, null=True)),
                ('UDGIS_MASK_BASEMAP', models.CharField(blank=True, null=True)),
                ('UDSATELLITE_DATA', models.CharField()),
                ('UDWEATHER_DATA', models.CharField(blank=True, null=True)),
                ('UDHISTORICAL_DATA', models.CharField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WCProjectInformationAndInputs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PROJECT_ID', models.CharField(max_length=50, unique=True)),
                ('PROJECT_NAME', models.CharField(max_length=50)),
                ('CREATION_DATE', models.DateField(auto_now_add=True)),
                ('CREATION_TIME', models.TimeField(auto_now_add=True)),
                ('CREATED_BY', models.CharField(blank=True, null=True)),
                ('PROJECT_DESCRIPTION', models.TextField(blank=True, max_length=200, null=True)),
                ('CLIENT_ORGANIZATION', models.CharField(max_length=50)),
                ('EXECUTED_ORGANIZATION', models.CharField(max_length=50)),
                ('CROPPING_YEAR', models.CharField(blank=True, null=True)),
                ('CROPPING_SEASON', models.CharField(blank=True, null=True)),
                ('AREA_INFORMATION', models.TextField(blank=True, null=True)),
                ('WORKSPACE_LOCATION', models.CharField()),
                ('PROJECT_FOLDER', models.CharField()),
                ('PROJECT_INFORMATION', models.CharField()),
                ('AREA_OF_INTEREST', models.CharField(blank=True, null=True)),
                ('GROUND_TRUTH', models.CharField(blank=True, null=True)),
                ('GIS_MASK_BASEMAP', models.CharField(blank=True, null=True)),
                ('SATELLITE_DATA', models.CharField()),
                ('WEATHER_DATA', models.CharField(blank=True, null=True)),
                ('HISTORICAL_DATA', models.CharField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WCProjectManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ADMIN_USER', models.CharField(null=True)),
                ('WORK_ASSIGN_USER', models.CharField(blank=True, null=True)),
                ('STACKING', models.CharField(blank=True, null=True)),
                ('UNSUPERVISED_CLASSIFICATION', models.CharField(blank=True, null=True)),
                ('SUPERVISED_CLASSIFICATION', models.CharField(blank=True, null=True)),
                ('RECODE_CLUMP_ELIMINATE', models.CharField(blank=True, null=True)),
                ('ANALYSIS', models.CharField(blank=True, null=True)),
                ('STATISTICS', models.CharField(blank=True, null=True)),
                ('PROJECT_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ProjectManagement', to='createproject.wcprojectinformationandinputs', to_field='PROJECT_ID')),
            ],
        ),
        migrations.CreateModel(
            name='UDProjectManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UD_ADMIN_USER', models.CharField(null=True)),
                ('UD_WORK_ASSIGN_USER', models.CharField(blank=True, null=True)),
                ('UD_STACKING', models.CharField(blank=True, null=True)),
                ('UD_UNSUPERVISED_CLASSIFICATION', models.CharField(blank=True, null=True)),
                ('UD_SUPERVISED_CLASSIFICATION', models.CharField(blank=True, null=True)),
                ('UD_RECODE_CLUMP_ELIMINATE', models.CharField(blank=True, null=True)),
                ('UD_ANALYSIS', models.CharField(blank=True, null=True)),
                ('UD_STATISTICS', models.CharField(blank=True, null=True)),
                ('UD_PROJECT_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UDProjectManagement', to='createproject.udprojectinformationandinputs', to_field='UDPROJECT_ID')),
            ],
        ),
    ]
