# Generated by Django 4.2.5 on 2025-04-15 11:34

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='zipinfo',
            fields=[
                ('zip_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('CL_REF', models.CharField(max_length=50)),
                ('CL_ORDNA', models.CharField(max_length=50)),
                ('CL_PROJNA', models.CharField(max_length=100)),
                ('CL_PURPOSE', models.CharField(max_length=100)),
                ('CL_ADDRESS1', models.CharField(max_length=150)),
                ('CL_ADDRESS2', models.CharField(max_length=150)),
                ('comman_area_shape', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
                ('COMP_NA', models.CharField(max_length=50)),
                ('Insert_DATE', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='MarsMainTableData',
            fields=[
                ('DATACODE', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('DATANAME', models.CharField(max_length=100)),
                ('COMP_NA', models.CharField(max_length=50)),
                ('SATT_NA', models.CharField(max_length=50)),
                ('CL_REF', models.CharField(max_length=50)),
                ('CL_ORDNA', models.CharField(max_length=50)),
                ('CL_PROJNA', models.CharField(max_length=100)),
                ('CL_PURPOSE', models.CharField(max_length=100)),
                ('CL_ADDRESS1', models.CharField(max_length=150)),
                ('CL_ADDRESS2', models.CharField(max_length=150)),
                ('SEN_NAME', models.CharField(max_length=20)),
                ('IMG_DATYPE', models.CharField(max_length=30)),
                ('IMG_DAPROC', models.CharField(max_length=20)),
                ('IMG_DATE', models.DateField()),
                ('IMG_DT_RNG', models.CharField(max_length=21)),
                ('DLOCA_CY', models.CharField(max_length=100)),
                ('DLOCA_ST', models.CharField(max_length=100)),
                ('DLOCA_DT', models.CharField(max_length=100)),
                ('DLOCA_LOCA', models.CharField(max_length=100)),
                ('DAREA', models.FloatField()),
                ('DSIZE', models.CharField(max_length=10)),
                ('DQLNAME', models.CharField(max_length=100)),
                ('DFORMAT', models.CharField(max_length=20)),
                ('DCLOUD', models.FloatField()),
                ('DSNOW', models.FloatField()),
                ('D_AQ_BITS', models.IntegerField()),
                ('D_PR_BITS', models.IntegerField()),
                ('DPRJ_TABLE', models.CharField(max_length=20)),
                ('DPRJ_NAME', models.CharField(max_length=6)),
                ('D_NROWS', models.IntegerField()),
                ('D_NCOLS', models.IntegerField()),
                ('D_NBANDS', models.IntegerField()),
                ('D_NTILES', models.IntegerField()),
                ('D_TYPE', models.CharField(max_length=20)),
                ('D_NBITS', models.IntegerField()),
                ('D_SIGN', models.CharField(max_length=10)),
                ('D_IN_ANGL', models.FloatField()),
                ('D_GSD_AXT', models.FloatField()),
                ('D_GSD_ALT', models.FloatField()),
                ('D_PIXELX', models.FloatField()),
                ('D_PIXELY', models.FloatField()),
                ('AL_DA_PATH', models.CharField(max_length=150)),
                ('AL_SH_PATH', models.CharField(max_length=150)),
                ('AL_QL_PATH', models.CharField(max_length=150)),
                ('XML_FILE', models.CharField(max_length=100, unique=True)),
                ('IMG_PREVIEW', models.ImageField(default=None, null=True, upload_to='PREVIEW/')),
                ('SAT_NO', models.CharField(max_length=50, null=True)),
                ('geometry_shape', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
                ('zipinfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zipinfo_set', to='archival.zipinfo')),
            ],
        ),
        migrations.CreateModel(
            name='MarsBandInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BAND_NAME', models.CharField(max_length=30)),
                ('BAND_S_SPEC', models.FloatField()),
                ('BAND_E_SPEC', models.FloatField()),
                ('DATACODE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marsbandinformation_set', to='archival.marsmaintabledata')),
            ],
        ),
        migrations.AddConstraint(
            model_name='marsmaintabledata',
            constraint=models.UniqueConstraint(fields=('DATACODE',), name='unique_datacode'),
        ),
    ]
